### ISSUE TITLE
[Bug] Not working anymore (again)

### ISSUE THREAD

**Issue by NyxIsBad** [E-boi/powercord-dateviewer#2]
Same issue as last time; area is defined, no date showing up. betterdiscord dateviewer is also currently broken
https://i.imgur.com/iPd3uo5.png

**Comment by E-boi** [comment]
hopefully it's fixed, update the plugin. If it is fixed you can close issue

**Comment by NyxIsBad** [comment]
Seems fixed, although there's now some css issue 
```css
.membersWrap-2h-GB4 > .members-1998pB{
  height: calc(100% - 95px);
}
``` 
missing
